name: ❓ Question
description: Ask a question about Oxford Dictionary Lookup
title: "[Question]: "
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        Have a question about how Oxford Dictionary Lookup works? We're here to help!

  - type: textarea
    id: question
    attributes:
      label: Your question
      description: What would you like to know about Oxford Dictionary Lookup?
      placeholder: "Example: How do I change the keyboard shortcut from Ctrl+Shift+X to something else?"
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Any other details that might help us answer your question
      placeholder: "Optional - What you've tried, screenshots, or related information"

  - type: checkboxes
    id: checklist
    attributes:
      label: Before submitting
      options:
        - label: I have searched existing issues for similar questions
          required: true
